### ISSUE TITLE
I would like to attempt implementing multi-deck adding

### ISSUE THREAD

**Issue by Frodoking21** [sviatoslav-lebediev/anki-quizlet-importer-extended#107]
Would you guys be receptive if I were to attempt developing support for importing multiple decks at once?

Disclaimer: This is my first time contributing to a github repo; I apologize if this is the wrong place to ask about something like this.

**Comment by sviatoslav-lebediev** [comment]
Hi, no worries that's the correct place to ask :) As for the proposition - could you explain a little bit? Do you want to give an opportunity to paste more than one link and import them one by one? My only concern is how to handle errors, what if we can't for some reason import some deck in the middle of the list, we will need to ask a user what to do next...

**Comment by Frodoking21** [comment]
Hi there, Thanks for the quick response

I'm thinking the user has the option to include multiple deck URL's in the Quizlet URL box by separating them with spaces, which the program then downloads sequentially. 

As for error handling. I'm thinking we could give the user a few choices. 1. skip failed deck and proceed or 2. Cancel operation. I'm now realizing though that if it successfully does some of them but not all, that could get messy really fast. Maybe we could check if the links are valid before attempting the import?

**Comment by sviatoslav-lebediev** [comment]
The problem is that it's more complicated than it looks :) We definitely can/should check links before we start the import but we can have a situation like this https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/108 when in the middle of importing one link we failed, we can check a `Skip errors` checkbox but do I want to skip errors for all decks, maybe not. What to do with the start/stop phrases, do we need to use them for all links or not, the same about the HTML field... Maybe we even need to hide some fields when users put more than 1 link, I don't know. The question is if it's worth doing this? :) I'm asking because I'm not a Python dev so I'm trying to keep the add-on as simple as possible.

**Comment by Frodoking21** [comment]
Fair Enough, I'm not a Python Dev either. Only a 2nd year undergrad who knows a bit of Java. I may just try to get it doing what I want it to do without any error handling and let you do with it as you choose. Leaving it is fine with me.

**Comment by sviatoslav-lebediev** [comment]
Hi, np
