### ISSUE TITLE
Downloaded out of order

### ISSUE THREAD

**Issue by lb312** [sviatoslav-lebediev/anki-quizlet-importer-extended#119]
I was able to convert the quizlet deck to anki but the cards are out of order in anki. Is there any way to fix this? Quizlet link below.

https://quizlet.com/510915469/pharmacokinetics-pt-1-flash-cards/?funnelUUID=16d75521-8f4c-48ae-a046-0dc41599c6c3

**Comment by sviatoslav-lebediev** [comment]
Hi, could you add more details ? Do you see them out of order when you study or in a list (when you click on a `Browse` button in Anki) ? I guess it's the first case - so I would check your study settings for that deck because Anki provides an order option.

p.s. I've tried to download your deck and the order is correct

**Comment by lb312** [comment]
Thank you so much for the quick response! They are out of order when I click Browse. My goal is to modify the ones I convert from Quizlet, but since they are out of order it is taking much longer than it needs to. I've looked at the settings to try to filter them in certain ways but nothing has worked.

I will try deleting and redownloading the add-on to see if that helps. Do you know of any settings that would re-order them in the Browse function?

Best,

Lauren Baetje
B.A./M.D. | Class of 2026
UMKC School of Medicine
________________________________

**Comment by sviatoslav-lebediev** [comment]
I would try to use this https://ankiweb.net/shared/info/874215009 and click on Due or Created
![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/727a90d2-4f94-404c-a746-c9c199f05b19)
but i think you just need to re-import this deck, because the add-on doesn't shuffle them during the  import.

**Comment by lb312** [comment]
That worked, thank you so much for your help.

Lauren Baetje
B.A./M.D. | Class of 2026
UMKC School of Medicine
________________________________

**Comment by sviatoslav-lebediev** [comment]
cool, happy to help
