### ISSUE TITLE
Keep getting the captcha error when I don't have a VPN

### ISSUE THREAD

**Issue by Lemsicle** [sviatoslav-lebediev/anki-quizlet-importer-extended#13]
Hi! Not sure how GitHub works, made an account just to report this issue since it seems like a more uncommon one.

I've been getting the captcha error for pretty much any deck I try to import, and I keep getting this error even though I don't have a VPN. I've used this add-on in the past (before Quizlet changed their website and it had to be fixed) and I've never received this error before. I saw that there was another post by someone here with the same issue, but since I'm at home I can't really "switch" my wi-fi.

**Comment by Lemsicle** [comment]
I see. I’m using Windows 10, i actually tried using the addon on another computer (also Windows 10) and I got the same error as well so that makes sense.

**Comment by sviatoslav-lebediev** [comment]
could you send me a link to the deck that you are trying to import?

**Comment by Lemsicle** [comment]
https://quizlet.com/522975461/ap-ch-1-flash-cards/ here’s one deck that i tried to import

**Comment by sviatoslav-lebediev** [comment]
thx, I will take a look

**Comment by Lemsicle** [comment]
Thanks. and to clarify, it's not just that one deck, I've tried to import different decks on that same account and none have worked. you're free to check out any of the other decks on there as well

**Comment by sviatoslav-lebediev** [comment]
The problem is that I actually can download your deck. 
Have you configured your plugin settings ?

```
To download private or password-protected sets, go to Tools - Add-ons - Improved Quizlet ... - Config and either set "cookies" or "qlts" and click OK.
To set "cookies", open Chrome DevTools, click the Network tab, reload the page or press Ctrl+R, click on the first request and copy "cookies" value from the request headers.
To set "qlts", open Chrome DevTools, click the Application tab, and copy "qlts" value from the Cookies pane - https://developers.google.com/web/tools/chrome-devtools/storage/cookies.
If "qlts" is set, it takes precedence over "cookies". Once it's done it should be possible to download private or password-protected sets for a limited period of time without making them public.
```

**Comment by Lemsicle** [comment]
I have not configured them. and I can't seem to figure out how to do it from those instructions (unfortunately i have 0 experience with this kind of stuff), I either can't find the values or am pasting the wrong ones into the addon because it keeps giving me an error. if you could provide a more detailed set of instructions i might be able to do it?

**Comment by Lemsicle** [comment]
hey! again, I don't know anything about coding but I saw the 403 error at the bottom of Chrome DevTools actually, even though the page itself loaded fine. could this be related to the issue?

![image](https://user-images.githubusercontent.com/71047075/92802807-d4d23500-f384-11ea-9d36-640657a18f63.png)

**Comment by sviatoslav-lebediev** [comment]
That's a different one. Tomorrow I will create a short video how to configure plugin and will share with you

**Comment by Lemsicle** [comment]
Thanks, I really appreciate it

**Comment by sviatoslav-lebediev** [comment]
![image](https://user-images.githubusercontent.com/19693768/92908307-c9d3df00-f42e-11ea-8696-4a09094c288d.png)
![image](https://user-images.githubusercontent.com/19693768/92908517-f7208d00-f42e-11ea-8515-7cfab14d332b.png)

I think these 2 screenshots will help you to add a config but I don't think that this will fix your problem because your decks are not private I think. you have mentioned that VPN helped you, so it looks like that's a network issue :( maybe you have some kind of proxy and Quizlet doesn't allow it to download decks. so maybe you need to use VPN for downloading :(

**Comment by Lemsicle** [comment]
Yeah, I was able to add the config but it didn't do anything, it keeps saying there's a captcha. It's just weird because it used to work fine and I never had this error.

**Comment by sviatoslav-lebediev** [comment]
I think that something has been changed in your network settings, it would be interesting if could try to use a different WI-FI. as for the add on config - we need it just for private decks

**Comment by kelciour** [comment]
Maybe try to use Fiddler as a proxy to see if it makes any difference - https://imgur.com/a/dWjPTTf
If there're no captured requests, try to restart Anki.

**Comment by sviatoslav-lebediev** [comment]
As I can see the original add on supports copy/paste a page source code, I will try to add this mode to my version as well in a few days

**Comment by Lemsicle** [comment]
Downloaded Fiddler, seems like it didn't do anything. :( Here's what I got:

![image](https://user-images.githubusercontent.com/71047075/93024134-14399500-f5c2-11ea-9813-b4b8561a645c.png)

**Comment by kelciour** [comment]
@sviatoslav-lebediev I don't know, maybe it'll be just a waste of time, but if it helps the relevant changes are in a separate branch on GitHub - https://github.com/kelciour/improved-quizlet-to-anki-21-importer/commit/20c1dc77e4e262bd202850aa6ab94a6f04da2afb

I only added it as a possible workaround for the same captcha error, but it probably will only work for text-based sets and any picture or audio downloads might be still blocked with 403 Forbidden.

@Lemsicle if you'd like to give it a try, temporarily install https://ankiweb.net/shared/info/538351043, restart Anki, open the add-on, paste the Quizlet URL and press Ctrl+U instead of clicking Import Deck, then open the same Quizlet set in the web browser, press Ctrl+U, copy its source code, go back to the add-on and paste it in the window.

Maybe try it with a set that contains some pictures - https://quizlet.com/25757408/ap-art-history-greek-art-flash-cards/

![image](https://user-images.githubusercontent.com/16260735/93025017-3d2e4a00-f603-11ea-8cc0-1f2ab4bee186.png)

About Fiddler, it looks like it's working, but the captured #40 request doesn't seem to be from the add-on as it returned 200 OK.

Try to use the add-on again with Fiddler, but at first enable Fiddler - Settings > HTTPS > Capture HTTPS traffic option, click Save, close it, and then use the add-on. 

There should be one HTTP request to quizlet.com:443 and after that HTTPS request to https://quizlet.com/522975461/flashcards

![image](https://user-images.githubusercontent.com/16260735/93024885-41a63300-f602-11ea-9dbe-81361bcc1e95.png)

**Comment by sviatoslav-lebediev** [comment]
Hi @kelciour, yep it will help, I will try to add this mode to my fork as well. To be honest I would prefer merging these 2 add-ons because they have almost the same functionality, but it's up to you :)

**Comment by kelciour** [comment]
@sviatoslav-lebediev yeah, merging them would make perfect sense now, but I'd prefer to keep it as it is. 

It's just I have no interest in the Quizlet add-on, but since some Anki users were using it and there were no other alternatives last time, I didn't have a choice but to try and fix the add-on a few times and maybe add some new functionality in the meantime if I was interested to do it and it could be useful to me and somebody else, and it'd be great if we could get to the bottom of the current issue.

**Comment by Lemsicle** [comment]
ah, my bad! here's what I got from Fiddler this time:
![image](https://user-images.githubusercontent.com/71047075/93032769-3bfc1d80-f601-11ea-8501-d81c273fc9f9.png)

I also tried the ctrl + U thing on the OG addon and it worked, imported the deck with pictures and all!

**Comment by sviatoslav-lebediev** [comment]
@Lemsicle cool I will add ctrl+u functionality to my version as well

**Comment by kelciour** [comment]
@sviatoslav-lebediev since it's working I merged it to the master branch and added a workaround for Ctrl+U on Ubuntu. For some reason, Ctrl+U on Ubuntu is being captured by QLineEdit and will cut the line to the clipboard and it's not listed on https://doc.qt.io/qt-5/qlineedit.html as one of the default key bindings.

@Lemsicle that's great!

If you're still interested or anyone else is interested, please update the original add-on with Tools - Add-ons - Check for Updates, restart Anki, restore your config file with Tools - Add-ons - Improved Quizlet ... - Config - Restore Defaults - Ok, and use Fiddler to capture the same Quizlet url - https://quizlet.com/522975461/ap-ch-1-terms-flash-cards/ - with the add-on and with the web browser (in the incognito mode), After that, please save your requests with File - Save Archive - All Sessions as .saz archive and upload it somewhere, since Firefox Send is not available maybe https://gofile.io/ or https://siasky.net/ or https://wetransfer.com/ or anything else. The archive could be later opened and examined either with Fiddler Everywhere or Fiddler Classic.

I don't know if it'll help or not, but maybe it'll give us some ideas or maybe it'll be all for nothing.

**Comment by Lemsicle** [comment]
@kelciour Sorry I disappeared for a while! I was hit with a bunch of exams, among some other things. Would you still like the archive?

**Comment by kelciour** [comment]
@Lemsicle yes, sure, if it won't bother you too much.

I have no experience and almost no knowledge and don't know if just comparing requests and looking around for some clues will be fruitful or not. If nothing else, maybe it'll be possible to show the web page to the user, solve the captcha, save the cookies and use them with the add-on.

https://support.cloudflare.com/hc/en-us/articles/200170136-Understanding-Cloudflare-Challenge-Passage-Captcha-

**Comment by Lemsicle** [comment]
Okay, no problem! I just wanted to make sure in case you already got it from someone else. Here it is: https://gofile.io/d/NFunIk

**Comment by kelciour** [comment]
Thank you! Though it didn't help very much. The captured archive contained a few additional requests to https://eventlogger-k8s.quizlet.com with 403 response code but it doesn't seems to be relevant to our case as it seems to be just some usage statistics that were being sent to Quizlet after a web page was already successfully loaded or maybe when there were some interaction with the web page. It's probably related to Sumo Logic.

https://www.sumologic.com/press-release/quizlet-selects-sumo-logic-to-ensure-service-reliability/
https://www.sumologic.com/insight/what-is-kubernetes/
https://www.theregister.com/2014/05/23/google_containerization_two_billion/

And I'm not sure if repeating the same process again will produce different results. Quizlet works for me with the add-on and an empty config and if I open the same set in the web browser without any extensions by closing all incognito windows and opening a new incognito window as it's been shown in this 1-minute long recorded video with ShareX.

https://i.imgur.com/3ijQTC1.mp4

![image](https://user-images.githubusercontent.com/16260735/94339454-d0ec1700-0002-11eb-8b3b-cf2afce3bb87.png)

**Comment by Lemsicle** [comment]
Well, that sucks. I mean, at this point I think I'll be fine with using a VPN or copypasting the source code into the add-on to import decks. It's a minor inconvenience but it works. Regardless, is there anything else I can do to help at this point?

**Comment by kelciour** [comment]
The different approach probably would be to use Wireshark similar to Fiddler to intercept and compare HTTPS requests and eventually update the add-on to make requests similar to the web browser. But I have no experience with Wireshark, there might be some hidden obstacles, I don't know if it'll be possible to fix the add-on this way and can't help with it since I can't reproduce the issue myself.

But if you're still up for it, it took me a while, but I just updated Improved Quizlet to Anki 2.1 Importer and made a proof-of-concept to be possible to download the Quizlet set with the cookies after resolving the Cloudflare captcha.

1. Update or install the add-on https://ankiweb.net/shared/info/538351043 and restart Anki.
2. Open the add-on.
3. Paste a Quizlet url, e.g. 

    ```https://quizlet.com/516429408/japanese-transport-flash-cards/```

4. Press Ctrl+G.
5. Solve a captcha and press OK.

Maybe it'll work or maybe not.

**Comment by sviatoslav-lebediev** [comment]
Hi, here is my two cents:) If I'm not mistaken we don't have a huge amount of cases like this. So honestly I don't think we need to solve this issue and add any additional code to our plugins. The plugin should do 1 job and this job is moving data between Quizlet and Anki. Any additional code makes plugin and supports more complicated. As I understood user can fix this issue using a VPN, we can add this information to our plugin description.

**Comment by kelciour** [comment]
Hi, Sviatoslav. Yes, I agree with you. The code to solve the captcha challenge maybe will be useful later if it can solve the current issue, but it'd need to be refactored, maybe improved and maybe shows up automatically without pressing any extra keys. I reverted all relevant commits in the repository to keep the code as it used to be.

**Comment by Lemsicle** [comment]
I can confirm that using ctrl + G allowed me to solve the captcha and import the deck :)

**Comment by kelciour** [comment]
Thank you @Lemsicle for testing and confirming that it's working :)

**Comment by kelciour** [comment]
Accidentally was able to trigger the captcha error by trying to download
https://quizlet.com/515858716/japanese-shops-fruit-flash-cards
instead of
https://quizlet.com/515858716/japanese-shops-fruit-flash-cards/

It should be fixed now with https://github.com/kelciour/improved-quizlet-to-anki-21-importer/commit/79222634252d2e38a022201538b9f3090d181dce, the add-on https://ankiweb.net/shared/info/538351043 was updated and the fix might work for everyone else too.

It's just a temprorary fix but I doubt it'll stop working in the future and there's no need to try to do something more sophisticated.

Additional Info:
- [Burp Suite Community Edition](https://portswigger.net/burp)
- https://stackoverflow.com/q/62684468
- https://stackoverflow.com/q/64642845
- [https://blogs.akamai.com/sitr/2019/05](https://blogs.akamai.com/sitr/2019/05/bots-tampering-with-tls-to-avoid-detection.html)
- [python-requests-and-testing-with-wireshark](https://hussainaliakbar.github.io/restricting-tls-version-and-cipher-suites-in-python-requests-and-testing-with-wireshark/)

**Comment by VeganStudent** [comment]
> Accidentally was able to trigger the captcha error by trying to download
> https://quizlet.com/515858716/japanese-shops-fruit-flash-cards
> instead of
> https://quizlet.com/515858716/japanese-shops-fruit-flash-cards/
> 
> It should be fixed now with [kelciour/improved-quizlet-to-anki-21-importer@7922263](https://github.com/kelciour/improved-quizlet-to-anki-21-importer/commit/79222634252d2e38a022201538b9f3090d181dce), the add-on https://ankiweb.net/shared/info/538351043 was updated and the fix might work for everyone else too.
> 
> It's just a temprorary fix but I doubt it'll stop working in the future and there's no need to try to do something more sophisticated.
> 
> Additional Info:
> 
> * [Burp Suite Community Edition](https://portswigger.net/burp)
> * https://stackoverflow.com/q/62684468
> * https://stackoverflow.com/q/64642845
> * [https://blogs.akamai.com/sitr/2019/05](https://blogs.akamai.com/sitr/2019/05/bots-tampering-with-tls-to-avoid-detection.html)
> * [python-requests-and-testing-with-wireshark](https://hussainaliakbar.github.io/restricting-tls-version-and-cipher-suites-in-python-requests-and-testing-with-wireshark/)

Hey I'm new to Github, made an account so I can ask for help here but, how do you download this fix. I've already got the patch for Quizlet so I'm able to import flash cards from Quizlet onto Anki without issue. Referring to the mic support portion of it. I don't know any coding or anything required to do in order to get the mic feature working. I've downloaded the zip file, but what else am I suppose to do because there's no guide anywhere that tells you what to do with the zip file. Again I'm able to import flash cards from Quizlet I just want the audio support feature that comes with it in order to save a lot of time when it comes to importing flash cards from quizlet, as I got a lot of flash cards there.

**Comment by sviatoslav-lebediev** [comment]
@VeganStudent Hi, if you need audio support you should download this plugin https://ankiweb.net/shared/info/1362209126

**Comment by VeganStudent** [comment]
So I download that on top of the other quizlet add on, as I was seeing in the comments that some suggested downloading the other add on, and copying the source code to it in order to get the audio support. Also won't downloading both add ons interfere with each other?

**Comment by sviatoslav-lebediev** [comment]
If you don't have captcha errors I would recommend downloading the plugin that I mentioned before and check if it works for you. I don't think they can interfere somehow, but maybe they use the same deck and if the structure of the deck is different you will get an error (deck name is `Basic Quizlet Extended`).

**Comment by VeganStudent** [comment]
Checked out the add on and it doesn't work, still says behind a captcha. The other quizlet add on that's able to get passed this doesn't work for the quizlet with audio support add on. It doesn't seem to interfere, but they don't go hand in hand. If you're talking about the zip file that's what I was looking to download however I don't know anything about getting that installed and adding onto Anki. Like I said in my first comment downloaded the zip file but what do I do next?

**Comment by kelciour** [comment]
@VeganStudent for the add-on without audio support, did you use [the .ankiaddon file with Ctrl+G support](https://github.com/kelciour/improved-quizlet-to-anki-21-importer/releases/tag/v1.0.0-captcha) to manually solve the captcha? Because the AnkiWeb version (with a fix) doesn't seem to be working anymore or maybe I got it wrong right from the start and the fix didn't work at all.

**Comment by VeganStudent** [comment]
Yes I did, however it only works for that add on, and not the other quizlet add on with the audio.

**Comment by VeganStudent** [comment]
I'm trying to get the audio support installed with importing things from Quizlet so I can save a lot of time transferring my flash cards from there to Anki. I just want to know how to get it working, or to see if its possible to do so.

**Comment by sviatoslav-lebediev** [comment]
The audio add-on doesn't support any anti-captcha algorithms, so I'm not sure if it's easy to add to it.  Have you tried to use it with an enabled VPN? Do you still have this error?
