### ISSUE TITLE
[QUESTION] remove reversed cards

### ISSUE THREAD

**Issue by black-backdoor** [sviatoslav-lebediev/anki-quizlet-importer-extended#137]
The problem is, I have a few cards of which I only need one side, but I imported them with the Tag reversed: true. How do I remove them?

**Comment by sviatoslav-lebediev** [comment]
Hi, I would check the anki docs because it's not related to the add-on but if you want you can try to use a browser add-on and find all required notes using a search input (https://ankiweb.net/shared/info/874215009)
![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/ea733b48-587d-4928-ad18-a9f1e35aab1f)

**Comment by black-backdoor** [comment]
To correct my mistake:

I have added a few Cards from Quizlet (with the setting add reversed)
but there are notes of which I like to remove the reversed version

**Comment by sviatoslav-lebediev** [comment]
maybe the easiest way is to remove the deck that the add-on imported and re-import again? 
but I would backup that deck before removing it.

**Comment by black-backdoor** [comment]
thanks
