### ISSUE TITLE
Can I Try And Help Fix This Issue With The Audio Stuff Not Working?

### ISSUE THREAD

**Issue by geier0compling** [sviatoslav-lebediev/anki-quizlet-importer-extended#152]
I am fairly new to programming but I've been programming in Python for about 1 year now.

Anyway, your Add-On has been beyond helpful for my language learning studies and I would love to try and help contribute to fixing the audio issue. 

Do you by chance know what part of the code is causing the issue with the audio not downloading? 

Sorry if this is not the proper channel to ask this question.

Thank you for your consideration,

Matthew

**Comment by sviatoslav-lebediev** [comment]
Hi, it's a proper channel to propose some help :) As for the audio issue, it's not a part of the code it's more about how to bypass the Cloudflare protection. As for me, we have two options:
1. client-side. We need to detect that Cloudflare protects these URLs and propose a user to solve that Cloudflare "captcha",  somehow store "cookies,"... and use this info when we download audio.
2. server-side. When we see that this file is protected, we will use a server proxy that will be able to stream audio and bypass Cloudflare protection. I've added a prototype of this server, and you can try to test it following these steps https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/134#issuecomment-1872949223
I would recommend you try to use this proxy server approach, and if it works, please let me know. The only problem is that this approach can't be free, because I will need to pay for proxies and a server, and I can't even estimate how many people will use it.

**Comment by geier0compling** [comment]
Ah man, just got home from work to try this out, but looks like the add-on is off the Anki site and it's not allowing me to go through with the proxy server test.

Hope all is well! I would love to be able to help out in any way. Feel free to reach out for any tests I could run or anything I could do to help make things easier for you!!

Best regards,
Matthew

**Comment by geier0compling** [comment]
Heyyy, Just wanted to let you know that the proxy server approach worked perfectly today!

What a cool solution to bypassing the Cloudflare protection! 

Definitely let me know if I can run any other tests, I would love to continue to help out in any way!

**Comment by sviatoslav-lebediev** [comment]
Hi, cool thank you for testing. You can keep using this code but I don't think that I can immediately release it for all users, I've described why here https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/discussions/156. Please join the discussion and let me know what you think. 
I'm going to close this issue.

**Comment by sviatoslav-lebediev** [comment]
@geier0compling could you write me at  moro.programmer@gmail.com and I will send you an access key ? I want to protect this API
