### ISSUE TITLE
Failed import from Quizet. 

### ISSUE THREAD

**Issue by somnia0113** [sviatoslav-lebediev/anki-quizlet-importer-extended#158]
Okay, so I tried to enter the URL and also do the HTML way, and they both failed. This is what I saw in the debug code. Hope this part is helpful. 

  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

I didn't have any windows, which probably comes from the QT6 version of ANKI. But this is the debug code. 

Quizlet URL: https://quizlet.com/870191690/japanese-lesson-01-flash-cards/?i=1g5j4t&x=1jqt

Thank you. Hope this is enough.

**Comment by sviatoslav-lebediev** [comment]
Hi, 99% that's because of the audio issue, if you don't need audio - uncheck the `Download audio` checkbox. You can also check the `Skip errors` checkbox. The only problem is that you will not have audio as well :( If you need audio, please take a look at this discussion https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/discussions/156

p.s. here is your deck 
[Japanese Lesson 01.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/13920237/Japanese.Lesson.01.apkg.zip)

p.s.2 HTML approach should work 100% if you uncheck the `Download audio` checkbox

**Comment by somnia0113** [comment]
Oh my god! Thank you for importing the deck with the audio for me too! Yes, both methods do work if you uncheck the download audio.

**Comment by sviatoslav-lebediev** [comment]
You are welcome, if you need to import another deck with audio - send me a link
