### ISSUE TITLE
Issue with importing

### ISSUE THREAD

**Issue by rsisonline** [sviatoslav-lebediev/anki-quizlet-importer-extended#25]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.38 (355e4cd5) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-07-23 23:32:12
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩
 
Caught exception:
Traceback (most recent call last):
  File "anki/notes.py", line 106, in _fieldOrd
KeyError: 'FrontText'
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/Users/myuser/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 302, in onCode
    self.createDeck(deck)
  File "/Users/myuser/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 347, in createDeck
    note["FrontText"] = item["term"]
  File "anki/notes.py", line 114, in __setitem__
  File "anki/notes.py", line 108, in _fieldOrd
KeyError: 'FrontText'
 
Hopefully you can help me! Thanks for the really great add-on!

Here is the deck I am trying to import: https://quizlet.com/nl/558078335/learn-korean-with-bts-book-2-flash-cards/

**Comment by sviatoslav-lebediev** [comment]
Hi, I will take a look.

**Comment by sviatoslav-lebediev** [comment]
I've successfully imported your deck. 
![image](https://user-images.githubusercontent.com/19693768/126878732-76d5b4ef-4dc4-45c0-80da-5d5fd752cdf8.png)
![image](https://user-images.githubusercontent.com/19693768/126878835-b58b402c-4947-4748-8d5c-3647b8c17edc.png)


I think about 1 problem that you can have. Did you change somehow this note type `Basic Quizlet Extended`? You should not do this, otherwise, the add-on will not be able to import decks. I would try to remove this note type, the add-on will recreate it when you start importing next time. 


my version:

Version ⁨2.1.43 (0fbae6bc)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Mac Os

**Comment by sviatoslav-lebediev** [comment]
here is a similar issue https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/24

**Comment by rsisonline** [comment]
Oh I think I did! How do I fix it? Thank you so much for figuring it out so fast!

**Comment by sviatoslav-lebediev** [comment]
Try to rename `Basic Quizlet Extended`. the add-on should recreate it.

**Comment by rsisonline** [comment]
It worked! Thank you so much ♥️ Such a great add-on for language learning!

**Comment by sviatoslav-lebediev** [comment]
cool, happy to help :)
