### ISSUE TITLE
I cannot convert this quizlet deck 

### ISSUE THREAD

**Issue by leow01** [sviatoslav-lebediev/anki-quizlet-importer-extended#82]
Link to quizlet deck - https://quizlet.com/gb/803916215/english-language-a-level-flash-cards/

**Comment by sviatoslav-lebediev** [comment]
Could you please elaborate? What is the problem? Could you try to start the import process a few more times ?

**Comment by pesjak** [comment]
For me it's https://quizlet.com/410701297/minna-no-nihongo-lesson-8-flash-cards/.

Error was for captcha, but after 10+ tries, it started to work.

**Comment by sviatoslav-lebediev** [comment]
yep, quizlet blocks requests from time to time. I'm going to add a fix but it will take time.
So for now just try a few times

**Comment by sviatoslav-lebediev** [comment]
@leow01 np, I've just tried to import your deck (without audio because it can take time) https://quizlet.com/gb/803916215/english-language-a-level-flash-cards/  and it was successfully imported. So I would try to import a few more times. I've bought more proxies and as for me, now the add-on works better but still for some cases you need to retry a few times

**Comment by sviatoslav-lebediev** [comment]
I've added the ability to set Quizlet HTML manually. Try this approach and let me know if it works for your case. I will close this ticket, re-open it, or create a new one if you still can't import decks.
